### ISSUE TITLE
Include "unidentified developer" warning in installation instruction

### ISSUE THREAD

**Issue by xingyif** [JetBrains/intellij-scala-bundle#2]
Several users at ScalaBridge (NYC 2018) tried to install the bundle and were confused about the "unidentified developer" warning. They had to open the bundle from system preference. And they had to move the bundle to a different dir before using it, because of "[App Translocation](https://developer.apple.com/library/archive/technotes/tn2206/_index.html#//apple_ref/doc/uid/DTS40007919-CH1-TNTAG17)".

Consider that the users have no programming/ IntelliJ experience, it will be helpful to mention that the above is expected, and briefly include an instruction of the steps in the README.

**Comment by SethTisue** [comment]
eventually we hope to offer a signed bundle that will make this warning go away, but it won't happen right away, and the existing bundle is currently being publicized on Twitter, so I agree that this would be good to document in the meantime

**Comment by xingyif** [comment]
Happy to create a PR this week.

**Comment by pavelfatin** [comment]
We've implemented the creation & signing of DMG images for macOS, so now there are no problems with the "unidentified developer" or "app translocation" - you can simply download, extract, and run the app (in all the OSes).
