### ISSUE TITLE
Not able to allocate enough Heap

### ISSUE THREAD

**Issue by xingyif** [JetBrains/intellij-scala-bundle#5]
Also an issue found (when ScalaBridge mentors trying out the intellj scala bundle):

"When importing a sbt project, got an error about not being able to allocate enough heap. It builds OK from the command line, though."

Heap size can be manually increased by "Settings -> search 'sbt' -> Maximum heap size"
But can it be automated?

Or again, include in README before solving it, so that the temp solution is obvious.

**Comment by xingyif** [comment]
Temporarily solved by adding fix steps in README. Would still be helpful if we could find a way to avoid having this problem at all @pavelfatin @jastice

**Comment by pavelfatin** [comment]
That was because of the default 64bit-only-compatible Xmx setting for sbt, together with the bundled 32bit JDK.

We've bundled 64bit JDK, so the issue should be now fixed.
